on: [push]
name: AKSDeploy
env:
  LOCATION: eastus123
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@master

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # What-if for AKS deploy
    - name: whatif
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az deployment sub create -l $LOCATION --template-file $GITHUB_WORKSPACE/aks-deployment.bicep --parameters $GITHUB_WORKSPACE/aks-deployment.parameters.json --what-if
      
      # AKS deploy
    - name: deploy
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az deployment sub create -l $LOCATION --template-file $GITHUB_WORKSPACE/aks-deployment.bicep --parameters $GITHUB_WORKSPACE/aks-deployment.parameters.json
